### ISSUE TITLE
DB

### ISSUE THREAD

**Issue by finnie2006** [Sk1pzz/Discord-Python-Ticket-System#2]
Can i use Mysql instead

**Comment by Sk1pzz** [comment]
you can do it yourself too ;)

**Comment by finnie2006** [comment]
But can i use mysql if i change the strings to mysql in the bot files

**Comment by Sk1pzz** [comment]
I dont know how the MySQL syntax works

**Comment by finnie2006** [comment]
i use pterodactyl so

**Comment by Sk1pzz** [comment]
I am sure the syntax is the same but the db connection function is different
